/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/pages/canon_800d.glb 
Author: aaa888 (https://sketchfab.com/aaa888)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/canon-800d-51fcdf7e23c445f09cda5724423d1066
Title: Canon 800D
*/

import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";

export function Canon800d_Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/portfolio/canon_800d.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        material={materials.material_0}
        geometry={(nodes.Object_4 as Mesh).geometry}
        rotation={[Math.PI / 6, -Math.PI / 2 - Math.PI / 6, 0]}
      />
    </group>
  );
}

useGLTF.preload("/portfolio/canon_800d.glb");
