name: Deploy Portfolio to GitHub Pages
on: push
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - name: Checkout JuliaMarkdownJoy repository
        uses: actions/checkout@v3
        with:
          repository: Eric-Philippe/JuliaMarkdownJoy
          path: JuliaMarkdownJoy
      - name: Install Julia packages
        run: |
          julia --project=JuliaMarkdownJoy -e '
          using Pkg
          Pkg.add("ArgParse")
          Pkg.instantiate()'
      - name: Check that the projects markdown links are not dead
        run: julia --project=JuliaMarkdownJoy JuliaMarkdownJoy/src/run.jl test-dead-links -i _projects/
      - name: Check that the albums markdown links are not dead
        run: julia --project=JuliaMarkdownJoy JuliaMarkdownJoy/src/run.jl test-dead-links -i _albums/
      - name: Extract the projects information
        run: julia --project=JuliaMarkdownJoy JuliaMarkdownJoy/src/run.jl extract -i _projects/ -c _projects/config.json  -o projects.json
      - name: Extract the albums information
        run: julia --project=JuliaMarkdownJoy JuliaMarkdownJoy/src/run.jl extract -i _albums/ -c _albums/config.json  -o albums.json
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: updated-json
          path: ./projects.json ./albums.json
  build:
    needs: update-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Download updated JSON and put it at the root of the project
        uses: actions/download-artifact@v3
        with:
          name: updated-json
          path: ./
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_CD_TOKEN }}
          publish_dir: ./dist
